FROM node:22.15.1-alpine

# Set memory limit Node.js
ENV NODE_OPTIONS="--max-old-space-size=450"

WORKDIR /app
COPY package*.json ./
COPY node_modules ./node_modules

# install nodemon globally
RUN npm install -g nodemon

CMD ["nodemon", "./src/server.ts"]
