FROM node:22.15.1-alpine

# Set memory limit Node.js
ENV NODE_OPTIONS="--max-old-space-size=300"

WORKDIR /app
COPY package*.json ./
COPY node_modules ./node_modules

CMD ["node", "./send-email/index.js"]
